### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-receipt#10]
### Description

We should start using components from Design system library for the receipt as well, which means we need to upgrade to React 18 first.

This will likely need the same work as done in app-frontend and studio, to sum up;
- Rewrite unit tests from Enzyme/react-test-renderer
- Upgrade React-router to v6
- Fix potiential typing issues

### Additional Information

Related to 
- https://github.com/Altinn/altinn-studio/issues/8821
- https://github.com/Altinn/app-frontend-react/issues/12

**Comment by SandGrainOne** [comment]
This work has been started by the Studio Team.
