### ISSUE TITLE
Receipt doesn't load if there are no texts for selected language

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-receipt#151]
### Description of the bug

This bug was created based on a [Support case (private repo)](https://github.com/Altinn/altinn-support-private/issues/1373).

The user gets an almost completely blank page instead of a properly rendered receipt. The rendering fails if there are no text file for the user selected language. In the case above, the user has selected Nynorsk, but the app have texts only for Bokmål.

The Receipt application must be able to show the receipt using Bokmål if the user selected language is missing from the list of supported languages by the app.

### Steps To Reproduce

1. Log in to TT02 as 46886601549 (tenor login)
2. Select the person "POSSESSIV BILLETTLUKE" if asked to pick a reportee
3. Pick language Nynorsk or English
4. Visit the Archive section of the messagebox. 
5. Open one of the elements called "Tilgjengelig: formueinntekt-skattemelding-v2, 2022"
6. Observe that the messagebox is using the app id and not the app title/name.
7. Click the button "See submitted form"
8. Observe that you get a mostly empty page.

![image](https://github.com/Altinn/altinn-receipt/assets/2217340/e9ace198-8454-44e1-8e18-24d8701ed2a6)

### Additional Information

I do think we should to some degree enforce at least 3 languages for all apps, but we should still have some logic to pick a suitable language if the user preferred language is missing.

**Comment by acn-sbuad** [comment]
Duplicate of #88. Can we merge the issues and close one, @SandGrainOne @annerisbakk ?

**Comment by SandGrainOne** [comment]
Agreed

**Comment by SandGrainOne** [comment]
Tested now, with an app with no texts for English. Receipt manage to find the Norwegian texts instead.
