### ISSUE TITLE
Receipt app is not using the `altinnPersistentContext` cookie for current language

### ISSUE THREAD

**Issue by codemascot** [Altinn/altinn-receipt#259]
### Description of the bug

While working on the #151 we found that this app isn't using the `altinnPersistentContext` set by the altinn.no and calling the `/receipt/api/v1/users/current` API every time to get the current language set by the user, which isn't working well for now as the `/receipt/api/v1/users/current` API is caching the output and therefore this app isn't getting the very recent change made by the user regarding the language in the frontend.

### Steps To Reproduce

1.Log in to TT02 as 46886601549 (tenor login)
2. Select the person "POSSESSIV BILLETTLUKE" if asked to pick a reportee
3. Pick language any langauge, i.e. Nynorsk or English
4. Visit the Archive section of the messagebox.
5. Open one of the elements called "Tilgjengelig: formueinntekt-skattemelding-v2, 2022"
6. Observe that the messagebox is using the app id and not the app title/name.
7. Click the button "See submitted form"
8. Then go back to the "inbox" tab.
9. Change the language to something else.
10. Again visit the Archive section of the messagebox.
11. Open one of the elements called "Tilgjengelig: formueinntekt-skattemelding-v2, 2022"
12. Observe that the messagebox is using the app id and not the app title/name.
13. Click the button "See submitted form"
14. You'll see the language hasn't changed.

### Tasks

- [ ] Consider using the `altinnPersistentContext` cookie for now as the other app is using it.
- [ ] Also try to find something better than cookie(1.e local storage or session) for this purpose.

### Related Issue
- #151

**Comment by SandGrainOne** [comment]
Let's consider this completed. I had some strange behaviour with language switching between nb and en during one of my tests, but I've been unable to recreate the issue.
