### ISSUE TITLE
Remove use of Microsoft.AspNet.WebApi.Client

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-receipt#74]
## Description
The Microsoft.AspNet.WebApi.Client package is getting old. ~~The last version of the package was released in 2018.~~ (The package has been getting [updates](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/6.0.0-preview1#versions-body-tab).)  We use it for it's extension methods on HttpContent to deserialize http responses, but there might be more. 

The package has a dependency to `Newtonsoft`.

Up to date extension methods can be found in the System.Net.Http.Json namespace.

## Development tasks
- [x] Remove use of library in ProfileWrapper, StorageWrapper and RegisterWrapper in Receipt
- [x] QA
- [x] Regression test

## Acceptance criteria
- [x] No sign of Microsoft.AspNet.WebApi.Client in any platform-components

**Comment by SandGrainOne** [comment]
I did a search across all repositories under /Altinn and found a few references, but Receipt is the only application maintained by Core that still rely on the package.

**Comment by acn-sbuad** [comment]
regression test successful in at22
