### ISSUE TITLE
Enable container scanning for receipt

### ISSUE THREAD

**Issue by ghost** [Altinn/altinn-receipt#75]
## Description

Receipt is depending on Azure Container Registry for building the container. It is possible to create an application/service principal in AAD with AcrPull rights and use secrets in the pipeline. However, this has a maintenance overhead with credentials expiring. 

## Considerations

Should we use an azure ad application for accessing ACR, or should we wait for ACR to have public access functionality? The base image used for receipt is the same as the other components. 

## Development tasks

- [ ] Enable container scan for receipt

**Comment by acn-sbuad** [comment]
Container scan is [implemented through a Github Action](https://github.com/Altinn/altinn-receipt/actions/workflows/container-scan.yml). Closing issue as it is obsolete
