### ISSUE TITLE
The Receipt component should look for Norwegian texts as a fall back.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-receipt#88]
## Description
The Receipt component fails to load a receipt if the user has selected a language for which texts are unavailable. 

## To Reproduce
1. Use the TT02 environment
2. Log in as user 22035400781 (Level 2 is enough)
3. Ensure the user has selected English as prefered language
4. Open the following receipt: https://platform.tt02.altinn.no/receipt/50154851/9d4916a8-2d00-4a57-b862-972eda77dd28
5. Observe that the receipt never load completely. In the browser network log the response on the text resource call is 404.

## Expected behavior
The app should attempt to retrieve the `nb` (Bokmål) texts and load with those instead.

Maybe also display a message about missing language support?

## Additional info
Slack discussion:
https://altinn.slack.com/archives/C02ESDSTVGD/p1646901750100229

**Comment by acn-sbuad** [comment]
#151 is a duplicate. Closing this.
