### ISSUE TITLE
Receipt page has attachments list expanded by default

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/altinn-receipt#89]
## Describe the bug
When an app instance has more than 5 attachments, the receipt page is showing the list of attachments (expanded)

## To Reproduce
1. Start a new instance of an app that has attachment component in Studio / AT21
2. Add 5 or more attachments and submit the app instance
3. The receipt page displays a list of attachments that is expanded

## Expected behavior
If there are 5 or more attachments, the attachments list should be collapsed by default.

## Screenshots
![image](https://user-images.githubusercontent.com/49391725/64231994-516c4100-cef1-11e9-9174-4f2bf4a9322f.png)

## Additional info
App: tdd/apptest
Browser: Chrome 76
Env: dev.altinn.studio / AT21

**Comment by annerisbakk** [comment]
@Febakke Er denne fremdeles aktuell?

**Comment by Febakke** [comment]
Kobler på @Edavda og @olavflar som nå er designere på apps. De får ta den vurderingen 😄 

Liten sak, aner ikke hvor stort problem dette er eller om det fortsatt er tilfelle.

**Comment by SandGrainOne** [comment]
Not enough interest or feedback.
