### ISSUE TITLE
Update receipt to work with new text resource file structure

### ISSUE THREAD

**Issue by haakemon** [Altinn/altinn-receipt#9]
### Description

We are simplifying the structure of text resources, and will need to update Receipt app to handle this new structure.

The text resources will also be served from CDN via the new https://github.com/Altinn/altinn-app-texts instead of CosmosDB.

### Additional Information

See https://github.com/Altinn/app-frontend-react/issues/378 for details about new structure

**Comment by SandGrainOne** [comment]
The associated project were canceled.
